/**
 * @file img-header.c
 * @brief
 * 
 */

#include "libopencm3/cm3/vector.h"

#include "img-header.h"

const image_hdr_t image_hdr =
{
  .u16_image_magic       = IMAGE_MAGIC,
  .u16_image_hdr_version = IMAGE_VERSION_CURRENT,
  .u32_crc               = 0,          // populated as part of a post compilation step
  .u32_data_size         = 0,
  .u8_image_type         = 1,
  .u8_version_major      = 1,
  .u8_version_minor      = 0,
  .u8_version_patch      = 1,
  .u32_vector_addr       = (uint32_t)&vector_table,
  .u32_reserved          = 0,
  .cP_git_sha            = "GIT_SHA", // GIT_SHA is generated by CMake
};

